//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstitutoKhipuERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCarrera
    {
        public TCarrera()
        {
            this.TCurso = new HashSet<TCurso>();
            this.TEstudiante = new HashSet<TEstudiante>();
            this.TMatricula = new HashSet<TMatricula>();
            this.TModuloCarrera = new HashSet<TModuloCarrera>();
        }
    
        public string CodCarrera { get; set; }
        public string NomCarrera { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<TCurso> TCurso { get; set; }
        public virtual ICollection<TEstudiante> TEstudiante { get; set; }
        public virtual ICollection<TMatricula> TMatricula { get; set; }
        public virtual ICollection<TModuloCarrera> TModuloCarrera { get; set; }
    }
}
