//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstitutoKhipuERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCurso
    {
        public TCurso()
        {
            this.TMatriculaSemetre = new HashSet<TMatriculaSemetre>();
        }
    
        public string CodCurso { get; set; }
        public string NomCurso { get; set; }
        public Nullable<int> Horas { get; set; }
        public Nullable<int> Creditos { get; set; }
        public string CodModulo { get; set; }
        public string CodCarrera { get; set; }
    
        public virtual TCarrera TCarrera { get; set; }
        public virtual TModuloCarrera TModuloCarrera { get; set; }
        public virtual ICollection<TMatriculaSemetre> TMatriculaSemetre { get; set; }
    }
}
