//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstitutoKhipuERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMatriculaSemetre
    {
        public string CodMatriculaSemetre { get; set; }
        public string CodMatricula { get; set; }
        public string CodEstudiante { get; set; }
        public string CodCurso { get; set; }
        public string CodDocente { get; set; }
        public string Semestre { get; set; }
        public string NomCurso { get; set; }
        public Nullable<int> NotaPromedio { get; set; }
    
        public virtual TCurso TCurso { get; set; }
        public virtual TDocente TDocente { get; set; }
        public virtual TEstudiante TEstudiante { get; set; }
        public virtual TMatricula TMatricula { get; set; }
    }
}
