//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstitutoKhipuERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMatricula
    {
        public TMatricula()
        {
            this.TMatriculaSemetre = new HashSet<TMatriculaSemetre>();
        }
    
        public string CodMatricula { get; set; }
        public string CodEstudiante { get; set; }
        public string CodCarrera { get; set; }
        public string CodModulo { get; set; }
        public string Semestre { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual TCarrera TCarrera { get; set; }
        public virtual TEstudiante TEstudiante { get; set; }
        public virtual ICollection<TMatriculaSemetre> TMatriculaSemetre { get; set; }
        public virtual TModuloCarrera TModuloCarrera { get; set; }
    }
}
