//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCarrera", Namespace="http://schemas.datacontract.org/2004/07/InstitutoKhipuERP.SL.DataContract")]
    [System.SerializableAttribute()]
    public partial class TCarrera : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodCarreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomCarreraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCarrera {
            get {
                return this.CodCarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.CodCarreraField, value) != true)) {
                    this.CodCarreraField = value;
                    this.RaisePropertyChanged("CodCarrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomCarrera {
            get {
                return this.NomCarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.NomCarreraField, value) != true)) {
                    this.NomCarreraField = value;
                    this.RaisePropertyChanged("NomCarrera");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaTCarrera", Namespace="http://schemas.datacontract.org/2004/07/InstitutoKhipuERP.SL.DataContract", ItemName="TCarrera")]
    [System.SerializableAttribute()]
    public class ListaTCarrera : System.Collections.Generic.List<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCurso", Namespace="http://schemas.datacontract.org/2004/07/InstitutoKhipuERP.SL.DataContract")]
    [System.SerializableAttribute()]
    public partial class TCurso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodCarreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodCursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreditosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HorasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomCursoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCarrera {
            get {
                return this.CodCarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.CodCarreraField, value) != true)) {
                    this.CodCarreraField = value;
                    this.RaisePropertyChanged("CodCarrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCurso {
            get {
                return this.CodCursoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodCursoField, value) != true)) {
                    this.CodCursoField = value;
                    this.RaisePropertyChanged("CodCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodModulo {
            get {
                return this.CodModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.CodModuloField, value) != true)) {
                    this.CodModuloField = value;
                    this.RaisePropertyChanged("CodModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Creditos {
            get {
                return this.CreditosField;
            }
            set {
                if ((this.CreditosField.Equals(value) != true)) {
                    this.CreditosField = value;
                    this.RaisePropertyChanged("Creditos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Horas {
            get {
                return this.HorasField;
            }
            set {
                if ((this.HorasField.Equals(value) != true)) {
                    this.HorasField = value;
                    this.RaisePropertyChanged("Horas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomCurso {
            get {
                return this.NomCursoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomCursoField, value) != true)) {
                    this.NomCursoField = value;
                    this.RaisePropertyChanged("NomCurso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaTCurso", Namespace="http://schemas.datacontract.org/2004/07/InstitutoKhipuERP.SL.DataContract", ItemName="TCurso")]
    [System.SerializableAttribute()]
    public class ListaTCurso : System.Collections.Generic.List<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TDocente", Namespace="http://schemas.datacontract.org/2004/07/InstitutoKhipuERP.SL.DataContract")]
    [System.SerializableAttribute()]
    public partial class TDocente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApePaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodDocenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMaterno {
            get {
                return this.ApeMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeMaternoField, value) != true)) {
                    this.ApeMaternoField = value;
                    this.RaisePropertyChanged("ApeMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePaterno {
            get {
                return this.ApePaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApePaternoField, value) != true)) {
                    this.ApePaternoField = value;
                    this.RaisePropertyChanged("ApePaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodDocente {
            get {
                return this.CodDocenteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodDocenteField, value) != true)) {
                    this.CodDocenteField = value;
                    this.RaisePropertyChanged("CodDocente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaTDocente", Namespace="http://schemas.datacontract.org/2004/07/InstitutoKhipuERP.SL.DataContract", ItemName="TDocente")]
    [System.SerializableAttribute()]
    public class ListaTDocente : System.Collections.Generic.List<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TEstudiante", Namespace="http://schemas.datacontract.org/2004/07/InstitutoKhipuERP.SL.DataContract")]
    [System.SerializableAttribute()]
    public partial class TEstudiante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApePaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodCarreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodEstudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMaterno {
            get {
                return this.ApeMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeMaternoField, value) != true)) {
                    this.ApeMaternoField = value;
                    this.RaisePropertyChanged("ApeMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePaterno {
            get {
                return this.ApePaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApePaternoField, value) != true)) {
                    this.ApePaternoField = value;
                    this.RaisePropertyChanged("ApePaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCarrera {
            get {
                return this.CodCarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.CodCarreraField, value) != true)) {
                    this.CodCarreraField = value;
                    this.RaisePropertyChanged("CodCarrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEstudiante {
            get {
                return this.CodEstudianteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodEstudianteField, value) != true)) {
                    this.CodEstudianteField = value;
                    this.RaisePropertyChanged("CodEstudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaTEstudiante", Namespace="http://schemas.datacontract.org/2004/07/InstitutoKhipuERP.SL.DataContract", ItemName="TEstudiante")]
    [System.SerializableAttribute()]
    public class ListaTEstudiante : System.Collections.Generic.List<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TMatricula", Namespace="http://schemas.datacontract.org/2004/07/InstitutoKhipuERP.SL.DataContract")]
    [System.SerializableAttribute()]
    public partial class TMatricula : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodCarreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodEstudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodMatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SemestreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCarrera {
            get {
                return this.CodCarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.CodCarreraField, value) != true)) {
                    this.CodCarreraField = value;
                    this.RaisePropertyChanged("CodCarrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEstudiante {
            get {
                return this.CodEstudianteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodEstudianteField, value) != true)) {
                    this.CodEstudianteField = value;
                    this.RaisePropertyChanged("CodEstudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodMatricula {
            get {
                return this.CodMatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodMatriculaField, value) != true)) {
                    this.CodMatriculaField = value;
                    this.RaisePropertyChanged("CodMatricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodModulo {
            get {
                return this.CodModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.CodModuloField, value) != true)) {
                    this.CodModuloField = value;
                    this.RaisePropertyChanged("CodModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Semestre {
            get {
                return this.SemestreField;
            }
            set {
                if ((object.ReferenceEquals(this.SemestreField, value) != true)) {
                    this.SemestreField = value;
                    this.RaisePropertyChanged("Semestre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaTMatricula", Namespace="http://schemas.datacontract.org/2004/07/InstitutoKhipuERP.SL.DataContract", ItemName="TMatricula")]
    [System.SerializableAttribute()]
    public class ListaTMatricula : System.Collections.Generic.List<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TMatriculaSemetre", Namespace="http://schemas.datacontract.org/2004/07/InstitutoKhipuERP.SL.DataContract")]
    [System.SerializableAttribute()]
    public partial class TMatriculaSemetre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodCursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodDocenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodEstudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodMatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodMatriculaSemetreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomCursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NotaPromedioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SemestreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCurso {
            get {
                return this.CodCursoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodCursoField, value) != true)) {
                    this.CodCursoField = value;
                    this.RaisePropertyChanged("CodCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodDocente {
            get {
                return this.CodDocenteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodDocenteField, value) != true)) {
                    this.CodDocenteField = value;
                    this.RaisePropertyChanged("CodDocente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEstudiante {
            get {
                return this.CodEstudianteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodEstudianteField, value) != true)) {
                    this.CodEstudianteField = value;
                    this.RaisePropertyChanged("CodEstudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodMatricula {
            get {
                return this.CodMatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodMatriculaField, value) != true)) {
                    this.CodMatriculaField = value;
                    this.RaisePropertyChanged("CodMatricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodMatriculaSemetre {
            get {
                return this.CodMatriculaSemetreField;
            }
            set {
                if ((object.ReferenceEquals(this.CodMatriculaSemetreField, value) != true)) {
                    this.CodMatriculaSemetreField = value;
                    this.RaisePropertyChanged("CodMatriculaSemetre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomCurso {
            get {
                return this.NomCursoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomCursoField, value) != true)) {
                    this.NomCursoField = value;
                    this.RaisePropertyChanged("NomCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NotaPromedio {
            get {
                return this.NotaPromedioField;
            }
            set {
                if ((this.NotaPromedioField.Equals(value) != true)) {
                    this.NotaPromedioField = value;
                    this.RaisePropertyChanged("NotaPromedio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Semestre {
            get {
                return this.SemestreField;
            }
            set {
                if ((object.ReferenceEquals(this.SemestreField, value) != true)) {
                    this.SemestreField = value;
                    this.RaisePropertyChanged("Semestre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaTMatriculaSemetre", Namespace="http://schemas.datacontract.org/2004/07/InstitutoKhipuERP.SL.DataContract", ItemName="TMatriculaSemetre")]
    [System.SerializableAttribute()]
    public class ListaTMatriculaSemetre : System.Collections.Generic.List<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TModuloCarrera", Namespace="http://schemas.datacontract.org/2004/07/InstitutoKhipuERP.SL.DataContract")]
    [System.SerializableAttribute()]
    public partial class TModuloCarrera : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodCarreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NroModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SemestreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCarrera {
            get {
                return this.CodCarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.CodCarreraField, value) != true)) {
                    this.CodCarreraField = value;
                    this.RaisePropertyChanged("CodCarrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodModulo {
            get {
                return this.CodModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.CodModuloField, value) != true)) {
                    this.CodModuloField = value;
                    this.RaisePropertyChanged("CodModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NroModulo {
            get {
                return this.NroModuloField;
            }
            set {
                if ((this.NroModuloField.Equals(value) != true)) {
                    this.NroModuloField = value;
                    this.RaisePropertyChanged("NroModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Semestre {
            get {
                return this.SemestreField;
            }
            set {
                if ((object.ReferenceEquals(this.SemestreField, value) != true)) {
                    this.SemestreField = value;
                    this.RaisePropertyChanged("Semestre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaTModuloCarrera", Namespace="http://schemas.datacontract.org/2004/07/InstitutoKhipuERP.SL.DataContract", ItemName="TModuloCarrera")]
    [System.SerializableAttribute()]
    public class ListaTModuloCarrera : System.Collections.Generic.List<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/InstitutoKhipuERP.SL.DataContract")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseñaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodUsuario {
            get {
                return this.CodUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodUsuarioField, value) != true)) {
                    this.CodUsuarioField = value;
                    this.RaisePropertyChanged("CodUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseñaField, value) != true)) {
                    this.contraseñaField = value;
                    this.RaisePropertyChanged("contraseña");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyServicioInstitutoKhipuERP.IServicioInstitutoKhipu")]
    public interface IServicioInstitutoKhipu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarTCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarTCarreraResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera insertarTCarrera(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarTCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarTCarreraResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera> insertarTCarreraAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarTCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarTCarreraResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera actualizarTCarrera(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarTCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarTCarreraResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera> actualizarTCarreraAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarTCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarTCarreraResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera eliminarTCarrera(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarTCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarTCarreraResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera> eliminarTCarreraAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCarreraResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera SeleccionarTCarrera(string CodCarrera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCarreraResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera> SeleccionarTCarreraAsync(string CodCarrera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCarreras", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCarrerasResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTCarrera SeleccionarTCarreras();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCarreras", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCarrerasResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTCarrera> SeleccionarTCarrerasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarTCurso", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarTCursoResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso insertarTCurso(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarTCurso", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarTCursoResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso> insertarTCursoAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarTCurso", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarTCursoResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso actualizarTCurso(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarTCurso", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarTCursoResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso> actualizarTCursoAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarTCurso", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarTCursoResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso eliminarTCurso(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarTCurso", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarTCursoResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso> eliminarTCursoAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCurso", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCursoResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso SeleccionarTCurso(string CodCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCurso", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCursoResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso> SeleccionarTCursoAsync(string CodCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCursos", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCursosResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTCurso SeleccionarTCursos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCursos", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTCursosResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTCurso> SeleccionarTCursosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarTDocente", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarTDocenteResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente insertarTDocente(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarTDocente", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarTDocenteResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente> insertarTDocenteAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarTDocente", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarTDocenteResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente actualizarTDocente(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarTDocente", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarTDocenteResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente> actualizarTDocenteAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarTDocente", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarTDocenteResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente eliminarTDocente(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarTDocente", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarTDocenteResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente> eliminarTDocenteAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTDocente", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTDocenteResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente SeleccionarTDocente(string CodDocente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTDocente", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTDocenteResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente> SeleccionarTDocenteAsync(string CodDocente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTDocentes", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTDocentesResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTDocente SeleccionarTDocentes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTDocentes", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTDocentesResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTDocente> SeleccionarTDocentesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarTEstudiante", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarTEstudianteResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante insertarTEstudiante(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarTEstudiante", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarTEstudianteResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante> insertarTEstudianteAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarTEstudiante", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarTEstudianteResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante actualizarTEstudiante(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarTEstudiante", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarTEstudianteResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante> actualizarTEstudianteAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarTEstudiante", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarTEstudianteResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante eliminarTEstudiante(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarTEstudiante", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarTEstudianteResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante> eliminarTEstudianteAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTEstudiante", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTEstudianteResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante SeleccionarTEstudiante(string CodEstudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTEstudiante", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTEstudianteResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante> SeleccionarTEstudianteAsync(string CodEstudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTEstudiantes", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTEstudiantesResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTEstudiante SeleccionarTEstudiantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTEstudiantes", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTEstudiantesResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTEstudiante> SeleccionarTEstudiantesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarTMatricula", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarTMatriculaResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula insertarTMatricula(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarTMatricula", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarTMatriculaResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula> insertarTMatriculaAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarTMatricula", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarTMatriculaResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula actualizarTMatricula(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarTMatricula", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarTMatriculaResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula> actualizarTMatriculaAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarTMatricula", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarTMatriculaResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula eliminarTMatricula(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarTMatricula", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarTMatriculaResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula> eliminarTMatriculaAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatricula", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatriculaResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula SeleccionarTMatricula(string CodMatricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatricula", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatriculaResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula> SeleccionarTMatriculaAsync(string CodMatricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatriculas", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatriculasResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTMatricula SeleccionarTMatriculas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatriculas", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatriculasResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTMatricula> SeleccionarTMatriculasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarTMatriculaSemetre", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarTMatriculaSemetreResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre insertarTMatriculaSemetre(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarTMatriculaSemetre", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarTMatriculaSemetreResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre> insertarTMatriculaSemetreAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarTMatriculaSemetre", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarTMatriculaSemetreResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre actualizarTMatriculaSemetre(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarTMatriculaSemetre", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarTMatriculaSemetreResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre> actualizarTMatriculaSemetreAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarTMatriculaSemetre", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarTMatriculaSemetreResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre eliminarTMatriculaSemetre(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarTMatriculaSemetre", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarTMatriculaSemetreResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre> eliminarTMatriculaSemetreAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatriculaSemetre", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatriculaSemetreResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre SeleccionarTMatriculaSemetre(string CodMatriculaSemetre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatriculaSemetre", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatriculaSemetreResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre> SeleccionarTMatriculaSemetreAsync(string CodMatriculaSemetre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatriculaSemetres", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatriculaSemetresResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTMatriculaSemetre SeleccionarTMatriculaSemetres(string pCodUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatriculaSemetres", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTMatriculaSemetresResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTMatriculaSemetre> SeleccionarTMatriculaSemetresAsync(string pCodUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarTModuloCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarTModuloCarreraResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera insertarTModuloCarrera(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarTModuloCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarTModuloCarreraResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera> insertarTModuloCarreraAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarTModuloCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarTModuloCarreraResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera actualizarTModuloCarrera(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarTModuloCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarTModuloCarreraResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera> actualizarTModuloCarreraAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarTModuloCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarTModuloCarreraResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera eliminarTModuloCarrera(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarTModuloCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarTModuloCarreraResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera> eliminarTModuloCarreraAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTModuloCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTModuloCarreraResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera SeleccionarTModuloCarrera(string CodModulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTModuloCarrera", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTModuloCarreraResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera> SeleccionarTModuloCarreraAsync(string CodModulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTModuloCarreras", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTModuloCarrerasResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTModuloCarrera SeleccionarTModuloCarreras();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTModuloCarreras", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/SeleccionarTModuloCarrerasResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTModuloCarrera> SeleccionarTModuloCarrerasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarUsuario", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarUsuarioResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario insertarUsuario(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/insertarUsuario", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/insertarUsuarioResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario> insertarUsuarioAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarUsuario", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarUsuarioResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario actualizarUsuario(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/actualizarUsuario", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/actualizarUsuarioResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario> actualizarUsuarioAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarUsuario", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarUsuarioResponse")]
        InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario eliminarUsuario(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/eliminarUsuario", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/eliminarUsuarioResponse")]
        System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario> eliminarUsuarioAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/ingresar", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/ingresarResponse")]
        string ingresar(string pCodUsuario, string pcontraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstitutoKhipu/ingresar", ReplyAction="http://tempuri.org/IServicioInstitutoKhipu/ingresarResponse")]
        System.Threading.Tasks.Task<string> ingresarAsync(string pCodUsuario, string pcontraseña);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioInstitutoKhipuChannel : InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.IServicioInstitutoKhipu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioInstitutoKhipuClient : System.ServiceModel.ClientBase<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.IServicioInstitutoKhipu>, InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.IServicioInstitutoKhipu {
        
        public ServicioInstitutoKhipuClient() {
        }
        
        public ServicioInstitutoKhipuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioInstitutoKhipuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioInstitutoKhipuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioInstitutoKhipuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera insertarTCarrera(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera request) {
            return base.Channel.insertarTCarrera(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera> insertarTCarreraAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera request) {
            return base.Channel.insertarTCarreraAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera actualizarTCarrera(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera request) {
            return base.Channel.actualizarTCarrera(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera> actualizarTCarreraAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera request) {
            return base.Channel.actualizarTCarreraAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera eliminarTCarrera(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera request) {
            return base.Channel.eliminarTCarrera(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera> eliminarTCarreraAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera request) {
            return base.Channel.eliminarTCarreraAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera SeleccionarTCarrera(string CodCarrera) {
            return base.Channel.SeleccionarTCarrera(CodCarrera);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCarrera> SeleccionarTCarreraAsync(string CodCarrera) {
            return base.Channel.SeleccionarTCarreraAsync(CodCarrera);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTCarrera SeleccionarTCarreras() {
            return base.Channel.SeleccionarTCarreras();
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTCarrera> SeleccionarTCarrerasAsync() {
            return base.Channel.SeleccionarTCarrerasAsync();
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso insertarTCurso(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso request) {
            return base.Channel.insertarTCurso(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso> insertarTCursoAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso request) {
            return base.Channel.insertarTCursoAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso actualizarTCurso(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso request) {
            return base.Channel.actualizarTCurso(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso> actualizarTCursoAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso request) {
            return base.Channel.actualizarTCursoAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso eliminarTCurso(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso request) {
            return base.Channel.eliminarTCurso(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso> eliminarTCursoAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso request) {
            return base.Channel.eliminarTCursoAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso SeleccionarTCurso(string CodCurso) {
            return base.Channel.SeleccionarTCurso(CodCurso);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TCurso> SeleccionarTCursoAsync(string CodCurso) {
            return base.Channel.SeleccionarTCursoAsync(CodCurso);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTCurso SeleccionarTCursos() {
            return base.Channel.SeleccionarTCursos();
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTCurso> SeleccionarTCursosAsync() {
            return base.Channel.SeleccionarTCursosAsync();
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente insertarTDocente(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente request) {
            return base.Channel.insertarTDocente(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente> insertarTDocenteAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente request) {
            return base.Channel.insertarTDocenteAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente actualizarTDocente(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente request) {
            return base.Channel.actualizarTDocente(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente> actualizarTDocenteAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente request) {
            return base.Channel.actualizarTDocenteAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente eliminarTDocente(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente request) {
            return base.Channel.eliminarTDocente(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente> eliminarTDocenteAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente request) {
            return base.Channel.eliminarTDocenteAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente SeleccionarTDocente(string CodDocente) {
            return base.Channel.SeleccionarTDocente(CodDocente);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TDocente> SeleccionarTDocenteAsync(string CodDocente) {
            return base.Channel.SeleccionarTDocenteAsync(CodDocente);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTDocente SeleccionarTDocentes() {
            return base.Channel.SeleccionarTDocentes();
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTDocente> SeleccionarTDocentesAsync() {
            return base.Channel.SeleccionarTDocentesAsync();
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante insertarTEstudiante(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante request) {
            return base.Channel.insertarTEstudiante(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante> insertarTEstudianteAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante request) {
            return base.Channel.insertarTEstudianteAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante actualizarTEstudiante(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante request) {
            return base.Channel.actualizarTEstudiante(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante> actualizarTEstudianteAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante request) {
            return base.Channel.actualizarTEstudianteAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante eliminarTEstudiante(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante request) {
            return base.Channel.eliminarTEstudiante(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante> eliminarTEstudianteAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante request) {
            return base.Channel.eliminarTEstudianteAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante SeleccionarTEstudiante(string CodEstudiante) {
            return base.Channel.SeleccionarTEstudiante(CodEstudiante);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TEstudiante> SeleccionarTEstudianteAsync(string CodEstudiante) {
            return base.Channel.SeleccionarTEstudianteAsync(CodEstudiante);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTEstudiante SeleccionarTEstudiantes() {
            return base.Channel.SeleccionarTEstudiantes();
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTEstudiante> SeleccionarTEstudiantesAsync() {
            return base.Channel.SeleccionarTEstudiantesAsync();
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula insertarTMatricula(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula request) {
            return base.Channel.insertarTMatricula(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula> insertarTMatriculaAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula request) {
            return base.Channel.insertarTMatriculaAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula actualizarTMatricula(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula request) {
            return base.Channel.actualizarTMatricula(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula> actualizarTMatriculaAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula request) {
            return base.Channel.actualizarTMatriculaAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula eliminarTMatricula(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula request) {
            return base.Channel.eliminarTMatricula(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula> eliminarTMatriculaAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula request) {
            return base.Channel.eliminarTMatriculaAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula SeleccionarTMatricula(string CodMatricula) {
            return base.Channel.SeleccionarTMatricula(CodMatricula);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatricula> SeleccionarTMatriculaAsync(string CodMatricula) {
            return base.Channel.SeleccionarTMatriculaAsync(CodMatricula);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTMatricula SeleccionarTMatriculas() {
            return base.Channel.SeleccionarTMatriculas();
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTMatricula> SeleccionarTMatriculasAsync() {
            return base.Channel.SeleccionarTMatriculasAsync();
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre insertarTMatriculaSemetre(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre request) {
            return base.Channel.insertarTMatriculaSemetre(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre> insertarTMatriculaSemetreAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre request) {
            return base.Channel.insertarTMatriculaSemetreAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre actualizarTMatriculaSemetre(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre request) {
            return base.Channel.actualizarTMatriculaSemetre(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre> actualizarTMatriculaSemetreAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre request) {
            return base.Channel.actualizarTMatriculaSemetreAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre eliminarTMatriculaSemetre(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre request) {
            return base.Channel.eliminarTMatriculaSemetre(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre> eliminarTMatriculaSemetreAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre request) {
            return base.Channel.eliminarTMatriculaSemetreAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre SeleccionarTMatriculaSemetre(string CodMatriculaSemetre) {
            return base.Channel.SeleccionarTMatriculaSemetre(CodMatriculaSemetre);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TMatriculaSemetre> SeleccionarTMatriculaSemetreAsync(string CodMatriculaSemetre) {
            return base.Channel.SeleccionarTMatriculaSemetreAsync(CodMatriculaSemetre);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTMatriculaSemetre SeleccionarTMatriculaSemetres(string pCodUsuario) {
            return base.Channel.SeleccionarTMatriculaSemetres(pCodUsuario);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTMatriculaSemetre> SeleccionarTMatriculaSemetresAsync(string pCodUsuario) {
            return base.Channel.SeleccionarTMatriculaSemetresAsync(pCodUsuario);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera insertarTModuloCarrera(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera request) {
            return base.Channel.insertarTModuloCarrera(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera> insertarTModuloCarreraAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera request) {
            return base.Channel.insertarTModuloCarreraAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera actualizarTModuloCarrera(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera request) {
            return base.Channel.actualizarTModuloCarrera(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera> actualizarTModuloCarreraAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera request) {
            return base.Channel.actualizarTModuloCarreraAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera eliminarTModuloCarrera(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera request) {
            return base.Channel.eliminarTModuloCarrera(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera> eliminarTModuloCarreraAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera request) {
            return base.Channel.eliminarTModuloCarreraAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera SeleccionarTModuloCarrera(string CodModulo) {
            return base.Channel.SeleccionarTModuloCarrera(CodModulo);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.TModuloCarrera> SeleccionarTModuloCarreraAsync(string CodModulo) {
            return base.Channel.SeleccionarTModuloCarreraAsync(CodModulo);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTModuloCarrera SeleccionarTModuloCarreras() {
            return base.Channel.SeleccionarTModuloCarreras();
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.ListaTModuloCarrera> SeleccionarTModuloCarrerasAsync() {
            return base.Channel.SeleccionarTModuloCarrerasAsync();
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario insertarUsuario(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario request) {
            return base.Channel.insertarUsuario(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario> insertarUsuarioAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario request) {
            return base.Channel.insertarUsuarioAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario actualizarUsuario(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario request) {
            return base.Channel.actualizarUsuario(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario> actualizarUsuarioAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario request) {
            return base.Channel.actualizarUsuarioAsync(request);
        }
        
        public InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario eliminarUsuario(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario request) {
            return base.Channel.eliminarUsuario(request);
        }
        
        public System.Threading.Tasks.Task<InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario> eliminarUsuarioAsync(InstitutoKhipuERP.PL.WinsForm.ProxyServicioInstitutoKhipuERP.Usuario request) {
            return base.Channel.eliminarUsuarioAsync(request);
        }
        
        public string ingresar(string pCodUsuario, string pcontraseña) {
            return base.Channel.ingresar(pCodUsuario, pcontraseña);
        }
        
        public System.Threading.Tasks.Task<string> ingresarAsync(string pCodUsuario, string pcontraseña) {
            return base.Channel.ingresarAsync(pCodUsuario, pcontraseña);
        }
    }
}
